# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_manual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='manual',
            name='path',
            field=models.FilePathField(blank=True, default=''),
        ),
    ]
