# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_manual', '0003_auto_20170617_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='tags',
            field=models.ManyToManyField(blank=True, to='key_manual.ManualTag'),
        ),
    ]
