# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_manual', '0004_auto_20170619_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='name_full',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
