# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_manual', '0005_manual_name_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='path',
            field=models.FilePathField(blank=True, match='\\.(?:pdf|doc|docx|xls|xlsx)$', null=True, path='/path_to_manuals/', recursive=True),
        ),
    ]
