# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('actual_date', models.DateField(blank=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalkey.CertificationCenter')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_begin', models.DateField(blank=True, null=True)),
                ('date_expire', models.DateField(blank=True, null=True)),
                ('renewal_time', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KeyAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalkey.KeyAssignment'),
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='cert_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cert_set', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='copy_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digitalkey.DigitalKey'),
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='employee_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeeGroup'),
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='key_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_set', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalkey.KeyLocation'),
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalkey.KeyType'),
        ),
    ]
