# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contragent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serial', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('expire', models.DateField()),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalKeyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('h', 'holder'), ('c', 'contact')], max_length=1)),
                ('contragent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contragent.Contragent')),
                ('digital_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalkey.DigitalKey')),
            ],
        ),
        migrations.CreateModel(
            name='KeyAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='contacts',
            field=models.ManyToManyField(through='digitalkey.DigitalKeyContact', to='contragent.Contragent'),
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='key_allocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalkey.KeyAllocation'),
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='key_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digitalkey.KeyType'),
        ),
    ]
