# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cert_center', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_begin', models.DateField(blank=True, null=True)),
                ('date_expire', models.DateField(blank=True, null=True)),
                ('renewal_time', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KeyAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digital_key.KeyAssignment'),
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='cert_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cert_center.CertificationCenter'),
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='cert_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cert_set', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='copy_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital_key.DigitalKey'),
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='employee_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeeGroup'),
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='key_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_set', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digital_key.KeyLocation'),
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digital_key.KeyType'),
        ),
    ]
