# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_key', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalkey',
            name='pin_admin',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='pin_container',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='digitalkey',
            name='pin_user',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
