# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_key', '0004_auto_20170626_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalkey',
            name='name_full',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='keyassignment',
            name='name_full',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='keylocation',
            name='name_full',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='worksystem',
            name='name_full',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='digitalkey',
            name='work_systems',
            field=models.ManyToManyField(blank=True, to='digital_key.WorkSystem'),
        ),
    ]
