# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_key', '0005_auto_20170629_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyassignment',
            name='work_systems',
            field=models.ManyToManyField(blank=True, to='digital_key.WorkSystem'),
        ),
    ]
