# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_key', '0006_keyassignment_work_systems'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalkey',
            name='cert_num',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
