# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cert_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert_center.CertificationCenter')),
            ],
        ),
        migrations.RemoveField(
            model_name='certrequirements',
            name='center',
        ),
        migrations.DeleteModel(
            name='CertRequirements',
        ),
    ]
