# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_center', '0002_auto_20170613_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationcenter',
            name='name_full',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='certrequirement',
            name='name_full',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
